In [2]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
import random
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'

iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])

Question1

In [3]:
A = np.array([[5, 3, 2], [4, 7, 2]])
B = np.array([[2, 1, 7], [6, 6, 5]])


print(A)
print(B)
vertical = np.vstack((A, B))

horizontal = np.hstack((A, B))

print("Vertically Stacked Array:\n", vertical)
print("\nHorizontally Stacked Array:\n", horizontal)

[[5 3 2]
 [4 7 2]]
[[2 1 7]
 [6 6 5]]
Vertically Stacked Array:
 [[5 3 2]
 [4 7 2]
 [2 1 7]
 [6 6 5]]

Horizontally Stacked Array:
 [[5 3 2 2 1 7]
 [4 7 2 6 6 5]]


Question2


In [4]:
common= np.intersect1d(A, B)

# Print result
print("Common Elements of A and B are :", common)

Common Elements of A and B are : [2 5 7]


Question 3


In [5]:
print("Numbers in the range of 5 to 10 in Array A:", A[(A >= 5) & (A <= 10)])
#print("Numbers in the range of 5 to 10 in Array B:", B[(B >= 5) & (B <= 10)])

Numbers in the range of 5 to 10 in Array A: [5 7]


Question 4


In [6]:
ans = iris_2d[(iris_2d[:, 2] > 1.5) & (iris_2d[:, 0] < 5.0)]

print(ans)

[[4.8 3.4 1.6 0.2]
 [4.8 3.4 1.9 0.2]
 [4.7 3.2 1.6 0.2]
 [4.8 3.1 1.6 0.2]
 [4.9 2.4 3.3 1. ]
 [4.9 2.5 4.5 1.7]]


Part 2 : Pandas
Question 1



In [7]:
url = 'https://raw.githubusercontent.com/selva86/datasets/master/Cars93_miss.csv'
df = pd.read_csv(url)

newdf = df.iloc[::20, :][['Manufacturer', 'Model', 'Type']]
print(newdf)


   Manufacturer    Model     Type
0         Acura  Integra    Small
20     Chrysler  LeBaron  Compact
40        Honda  Prelude   Sporty
60      Mercury   Cougar  Midsize
80       Subaru   Loyale    Small


Question 2



In [8]:
df.loc[:, 'Min.Price'] = df['Min.Price'].fillna(df['Min.Price'].mean())
df.loc[:, 'Max.Price'] = df['Max.Price'].fillna(df['Max.Price'].mean())

print(df[['Min.Price', 'Max.Price']].head())

   Min.Price  Max.Price
0  12.900000  18.800000
1  29.200000  38.700000
2  25.900000  32.300000
3  17.118605  44.600000
4  17.118605  21.459091


Question 3


In [9]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))

rows = df[df.sum(axis=1) > 100]
print(rows)

     0   1   2   3
0   33  17  31  27
4   33  26  33  22
7   37  20  21  25
8   25  36  14  29
12  32  34  12  38
13  27  34  34  14
14  27  39  39  10
